<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Platform EPCI CAPEX – Offshore Wind Infrastructure Model Assumptions</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-787e033c7b6f65c9dfccb6078e5d2d34.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../platforms/platform_material_capex.html">Platforms</a></li><li class="breadcrumb-item"><a href="../platforms/platform_material_capex.html">Platform EPCI CAPEX</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Offshore Wind Infrastructure Model Assumptions</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../positioning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Positioning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Methodology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodology</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/system_boundary_and_lcoe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">System Boundary and Carrier-Cost Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/financial_and_price_basis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Financial and Price-Basis Assumptions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/modelling_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelling Workflow</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/optimisation_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inputs, Parameters and Outputs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology/energy_availability_and_annualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Energy and Availability</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Architectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../architectures/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Architectures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../architectures/electricity_export_hvdc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Electricity Export with HVDC</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../architectures/centralised_hydrogen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Centralised Hydrogen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../architectures/decentralised_hydrogen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decentralised Hydrogen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../architectures/component_mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Component Mapping</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Wind Resource and Layout</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../wind_resource_and_layout/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wind Resource and Layout</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../wind_resource_and_layout/wind_resource_and_weibull.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wind Resource and Weibull Distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../wind_resource_and_layout/wake_modelling_and_spacing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wake Modelling and Spacing</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Turbine System</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../turbine_system/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turbine System</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../turbine_system/wind_turbine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wind Turbine Mass and Cost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../turbine_system/power_electronics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turbine Power Electronics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../turbine_system/foundation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Monopile Foundation Mass and Cost</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Electrical Infrastructure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Electrical Infrastructure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/power_conversion_equipment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Power Conversion Equipment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/infield_ac_cables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Infield AC Cables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/hvdc_converter_stations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HVDC Converter Stations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/hvdc_export_cables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HVDC Export Cables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../electrical_infra/onshore_grid_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Onshore Grid Connection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Hydrogen Production</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_production/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hydrogen Production</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_production/dc_integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DC Integration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_production/stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stack (PEM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_production/balance_of_plant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Balance of Plant</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_production/elx_power_electronics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Power Electronics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Hydrogen Infrastructure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_infra/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hydrogen Infrastructure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_infra/infield_infrastructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hydrogen Infield Infrastructure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_infra/compressor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hydrogen Compressor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_infra/hydrogen_pipelines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hydrogen Pipelines</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../hydrogen_infra/pipeline_pressure_and_capacity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pipeline Pressure and Capacity</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Platforms</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../platforms/platform_material_capex.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Platform EPCI CAPEX</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Offshore Installation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../offshore_installation/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Offshore Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../offshore_installation/turbine_and_foundation_installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Turbine and Foundation Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../offshore_installation/cable_and_pipeline_installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cable and Pipeline Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../offshore_installation/platform_and_substation_installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Platform and Substation Installation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References and Evidence Status</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#calculation-and-cost-boundary" id="toc-calculation-and-cost-boundary" class="nav-link active" data-scroll-target="#calculation-and-cost-boundary">Calculation and Cost Boundary</a></li>
  <li><a href="#why-use-the-combined-commercial-package" id="toc-why-use-the-combined-commercial-package" class="nav-link" data-scroll-target="#why-use-the-combined-commercial-package">Why Use the Combined Commercial Package?</a></li>
  <li><a href="#mass-basis-and-proposed-relationship" id="toc-mass-basis-and-proposed-relationship" class="nav-link" data-scroll-target="#mass-basis-and-proposed-relationship">Mass Basis and Proposed Relationship</a></li>
  <li><a href="#commercial-benchmarks-and-reproducible-comparison" id="toc-commercial-benchmarks-and-reproducible-comparison" class="nav-link" data-scroll-target="#commercial-benchmarks-and-reproducible-comparison">Commercial Benchmarks and Reproducible Comparison</a>
  <ul class="collapse">
  <li><a href="#published-costs-and-scope" id="toc-published-costs-and-scope" class="nav-link" data-scroll-target="#published-costs-and-scope">Published costs and scope</a></li>
  <li><a href="#reconstructed-comparison-on-the-common-price-basis" id="toc-reconstructed-comparison-on-the-common-price-basis" class="nav-link" data-scroll-target="#reconstructed-comparison-on-the-common-price-basis">Reconstructed comparison on the common price basis</a></li>
  <li><a href="#currency-and-price-year-audit" id="toc-currency-and-price-year-audit" class="nav-link" data-scroll-target="#currency-and-price-year-audit">Currency and price-year audit</a></li>
  <li><a href="#interpretation-and-tradeoffs" id="toc-interpretation-and-tradeoffs" class="nav-link" data-scroll-target="#interpretation-and-tradeoffs">Interpretation and Tradeoffs</a></li>
  <li><a href="#provisional-conclusion-and-further-evidence" id="toc-provisional-conclusion-and-further-evidence" class="nav-link" data-scroll-target="#provisional-conclusion-and-further-evidence">Provisional Conclusion and Further Evidence</a></li>
  </ul></li>
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example">Why the DNV Structural Model Is Not the Total-Cost Model</a></li>
  <li><a href="#executable-interface-output-and-applicability" id="toc-executable-interface-output-and-applicability" class="nav-link" data-scroll-target="#executable-interface-output-and-applicability">Executable Interface, Output and Applicability</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../platforms/platform_material_capex.html">Platforms</a></li><li class="breadcrumb-item"><a href="../platforms/platform_material_capex.html">Platform EPCI CAPEX</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Platform EPCI CAPEX</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="calculation-and-cost-boundary" class="level2">
<h2 class="anchored" data-anchor-id="calculation-and-cost-boundary">Calculation and Cost Boundary</h2>
<p>This page defines the implemented cost model for <strong>one central offshore platform</strong>: a commercial engineering, procurement, construction and installation (EPCI) package scaled by the equipment mass it accommodates. The output is total offshore platform EPCI CAPEX on the common EUR<sub>2025</sub> basis.</p>
<p>The package includes platform engineering, structural fabrication, yard integration, transport, offshore installation, hook-up and commissioning within the reference contract’s scope. These activities enter the project cost total <strong>once</strong>, through this package. A separate platform fabrication or installation estimate must not be added to it.</p>
<p>Hosted process and conversion equipment purchase remains with the component owners. Its mass drives platform sizing, but its purchase cost must be excluded from the platform benchmark before comparison. Cables, pipelines and their installation remain separate. Contract-level engineering and delivery allowances already embedded in EPCI must not be added again as project-wide allowances. Other owner costs remain outside this package.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Implemented commercial screening model
</div>
</div>
<div class="callout-body-container callout-body">
<p>The executable central-platform workflow now books one combined offshore EPCI cost. It accepts direct equipment mass or complete topside mass; it does not add DNV fabrication, yard-integration or platform-installation costs. The benchmark coefficient is an adopted screening judgement, not a fitted law. Previous models remain in the non-published archive and as inactive comparison helpers.</p>
<p>Platform CAPEX can be calculated independently of unresolved OPEX and decommissioning. Complete LCOH remains unavailable until all included cost inputs are supplied. Installation feasibility is reported as not assessed by this mass-cost calculation.</p>
</div>
</div>
</section>
<section id="why-use-the-combined-commercial-package" class="level2">
<h2 class="anchored" data-anchor-id="why-use-the-combined-commercial-package">Why Use the Combined Commercial Package?</h2>
<p>Commercial awards provide observable prices for delivered packages, but generally do not disclose a consistent split between platform materials, fabrication, integration and offshore installation. A detailed calculation of those components would require independently supported rates, durations, equipment inclusions and commercial allowances. The available evidence does not constrain that decomposition sufficiently.</p>
<p>For this model, fabrication and installation are procured as one delivered offshore EPCI scope. Their separation is unnecessary for the required total <strong>if their material cost drivers can be represented together</strong>. Our working hypothesis is that equipment mass drives topside size and the associated fabrication, integration and installation effort, making total EPCI approximately proportional to equipment mass over a comparable design range.</p>
<p>This is a modelling hypothesis, not an established scaling law. Fixed mobilisation costs, site conditions and changes in installation method can break proportionality. Combining scopes does not prove that each component scales linearly; the total relationship must be tested against additional commercial references. Until then, an aggregate relationship is more transparent than a detailed breakdown built from poorly constrained assumptions.</p>
</section>
<section id="mass-basis-and-proposed-relationship" class="level2">
<h2 class="anchored" data-anchor-id="mass-basis-and-proposed-relationship">Mass Basis and Proposed Relationship</h2>
<p>Let <span class="math inline">\(M_{\mathrm{eqp}}\)</span> be the hosted equipment mass in tonnes. It includes collection and conversion equipment, stacks, BOP, compressors and shared auxiliaries appropriate to the architecture. Collection switchgear remains included even though the model does not require a feeder-bay count. Equipment duties and inclusions must match those of the reference.</p>
<p>The implemented relationship is</p>
<p><span class="math display">\[
\boxed{C_{\mathrm{EPCI}}(M_{\mathrm{eqp}})
=C_{\mathrm{ref}}
\left(\frac{M_{\mathrm{eqp}}}{M_{\mathrm{eqp,ref}}}\right)^\beta.}
\]</span></p>
<p><span class="math inline">\(C_{\mathrm{ref}}\)</span> is a scope-matched offshore EPCI reference cost in EUR<sub>2025</sub>; <span class="math inline">\(M_{\mathrm{eqp,ref}}\)</span> is its equipment mass in tonnes; <span class="math inline">\(\beta\)</span> is a dimensionless cost-scaling exponent. The default is linear scaling (<span class="math inline">\(\beta=1\)</span>); recorded scenario overrides may vary the exponent. No fitted coefficient or exponent is claimed. The reference cost is <span class="math inline">\(C_{\mathrm{ref}}=k_{2025}M_{\mathrm{eqp,ref}}\)</span>, so changing <span class="math inline">\(\beta\)</span> preserves the cost at the reference mass.</p>
<p>Published platform weights commonly describe <strong>complete topsides</strong>, including structure, rather than equipment alone. If <span class="math inline">\(f_S\)</span> is the structural fraction of complete topside mass <span class="math inline">\(M_{\mathrm{top}}\)</span>, then</p>
<p><span class="math display">\[
M_{\mathrm{eqp}}=(1-f_S)M_{\mathrm{top}}.
\]</span></p>
<p>Consequently,</p>
<p><span class="math display">\[
C_{\mathrm{EPCI}}
=C_{\mathrm{ref}}
\left[\frac{(1-f_S)M_{\mathrm{top}}}
{(1-f_{S,\mathrm{ref}})M_{\mathrm{top,ref}}}\right]^\beta.
\]</span></p>
<p>With an equal structural fraction in the case and reference, this reduces to scaling by the ratio of complete topside masses. This preserves the link to commercial mass disclosures without treating topside mass as measured equipment mass. DNV’s 50% structural fraction is a provisional conversion assumption, not a supplier weight breakdown <span class="citation" data-cites="dnv2023OffshoreHydrogen">(<a href="#ref-dnv2023OffshoreHydrogen" role="doc-biblioref">DNV 2023, sec. 3.4</a>)</span>. Differences between HVDC and electrolysis structural fractions remain a source of uncertainty.</p>
<p>A separate upstream power-to-mass estimate may be needed where equipment mass is unavailable. Its exponent describes mass scaling with capacity and must not be confused with <span class="math inline">\(\beta\)</span>, which describes cost scaling with mass. No complete hydrogen equipment-mass reference or power-to-mass fit is adopted here.</p>
</section>
<section id="commercial-benchmarks-and-reproducible-comparison" class="level2">
<h2 class="anchored" data-anchor-id="commercial-benchmarks-and-reproducible-comparison">Commercial Benchmarks and Reproducible Comparison</h2>
<p>The evidence separates <strong>offshore EPCI awards</strong>, <strong>allocated framework costs</strong>, <strong>hydrogen design studies</strong>, and <strong>fabrication subcontracts</strong>. Only observations with comparable scope can calibrate the same cost relation. Published awards are historical contract values, not verified final outturn costs or current supplier quotations.</p>
<p>For a source cost <span class="math inline">\(C_y\)</span> in currency CU, annual-average exchange rate <span class="math inline">\(X_y\)</span> in CU/EUR, and annual euro-area HICP change <span class="math inline">\(\pi_j\)</span>, the preliminary normalisation is</p>
<p><span class="math display">\[
C_{2025}=\frac{C_y}{X_y}\prod_{j=y+1}^{2025}(1+\pi_j).
\]</span></p>
<p>For EUR-denominated evidence, <span class="math inline">\(X_y=1\)</span>. Where a price year is not stated, the award or publication year is an explicit assumption. This adjustment does not capture sector-specific escalation, contractual indexation, final settlement or changes in scope.</p>
<p>For each reference, equipment mass and specific costs follow as</p>
<p><span class="math display">\[
M_{\mathrm{eqp}}=(1-f_S)M_{\mathrm{top}},\qquad
k=\frac{C_{2025}}{M_{\mathrm{eqp}}},\qquad
c_P=\frac{C_{2025}}{10^6P_{\mathrm{GW}}},\qquad
m_P=\frac{M_{\mathrm{eqp}}}{10^6P_{\mathrm{GW}}}.
\]</span></p>
<p>Here <span class="math inline">\(k\)</span> is EUR<sub>2025</sub>/equipment tonne, <span class="math inline">\(c_P\)</span> is EUR<sub>2025</sub>/kW and <span class="math inline">\(m_P\)</span> is equipment t/kW. The factor <span class="math inline">\(10^6\)</span> converts GW to kW. These are package-specific ratios, not additional additive cost factors.</p>
<!-- Generated by tools/build_platform_benchmarks.py; edit inputs or builder. -->
<section id="published-costs-and-scope" class="level3">
<h3 class="anchored" data-anchor-id="published-costs-and-scope">Published costs and scope</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Reference</th>
<th>Capacity / count</th>
<th>Published package cost</th>
<th>Price-year basis</th>
<th>Scope and source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HKZ Alpha + Beta</td>
<td>2 × 0.7 GW</td>
<td>200.0 million USD</td>
<td>2019 (aggregate announcement; Alpha awarded earlier)</td>
<td>Offshore EPCI; owner-procured HV equipment. <span class="citation" data-cites="petrofac2019HKZ tennet2021OwnerEquipment">(<a href="#ref-petrofac2019HKZ" role="doc-biblioref">Petrofac 2019</a>; <a href="#ref-tennet2021OwnerEquipment" role="doc-biblioref">TenneT 2021</a>)</span></td>
</tr>
<tr class="even">
<td>Nederwiek 1</td>
<td>2 GW</td>
<td>1,400.0 million USD</td>
<td>2023 (award)</td>
<td>Petrofac share includes offshore and onshore works; offshore allocation is assumed. <span class="citation" data-cites="petrofac2023Nederwiek">(<a href="#ref-petrofac2023Nederwiek" role="doc-biblioref">Petrofac 2023b</a>)</span></td>
</tr>
<tr class="odd">
<td>Petrofac framework</td>
<td>6 systems</td>
<td>13,000.0 million EUR</td>
<td>2023 (announcement)</td>
<td>Both partners, both ends; allocated average is not an independent observation. <span class="citation" data-cites="petrofac2023Framework petrofac2025Prospectus">(<a href="#ref-petrofac2023Framework" role="doc-biblioref">Petrofac 2023a</a>, <a href="#ref-petrofac2025Prospectus" role="doc-biblioref">2025</a>)</span></td>
</tr>
<tr class="even">
<td>NSE / Iv concept</td>
<td>0.5 GW</td>
<td>161.0 million EUR</td>
<td>2022 (publication assumed)</td>
<td>Structure including installation, excluding process-equipment purchase. <span class="citation" data-cites="nse2022EnergyHubs">(<a href="#ref-nse2022EnergyHubs" role="doc-biblioref">North Sea Energy 2022</a>, table 4.9 and sec.&nbsp;4.4.2)</span></td>
</tr>
<tr class="odd">
<td>OffsH2ore concept</td>
<td>0.5 GW</td>
<td>140.9 million EUR</td>
<td>2023 (publication assumed)</td>
<td>Structure, piping and installation; further engineering allowance separate. <span class="citation" data-cites="offsh2ore2023Report">(<a href="#ref-offsh2ore2023Report" role="doc-biblioref">Fraunhofer ISE and project partners 2023, 79</a>)</span></td>
</tr>
<tr class="even">
<td>MHB Alpha subcontract</td>
<td>2 GW</td>
<td>1,200.0 million MYR</td>
<td>2023 (award)</td>
<td>Construction engineering, fabrication, mechanical completion, load-out, sea fastening and architectural work; not full EPCI. <span class="citation" data-cites="mhb2023AlphaAward">(<a href="#ref-mhb2023AlphaAward" role="doc-biblioref">Malaysia Marine and Heavy Engineering Holdings Berhad 2023</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="reconstructed-comparison-on-the-common-price-basis" class="level3">
<h3 class="anchored" data-anchor-id="reconstructed-comparison-on-the-common-price-basis">Reconstructed comparison on the common price basis</h3>
<p>All costs below are EUR<sub>2025</sub>. Equipment masses are inferred, not measured. HKZ is a per-platform average of one combined award; the framework uses Alpha’s mass as a representative reference, not six matched project weights.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Reference</th>
<th style="text-align: right;">Topside (t)</th>
<th style="text-align: right;">Inferred equipment (t)</th>
<th style="text-align: right;">Cost (million EUR<sub>2025</sub>)</th>
<th style="text-align: right;">EUR<sub>2025</sub>/equipment t</th>
<th style="text-align: right;">Equipment t/kW</th>
<th style="text-align: right;">EUR<sub>2025</sub>/kW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HKZ Alpha + Beta (average)</td>
<td style="text-align: right;">3,875</td>
<td style="text-align: right;">1,938</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">56,673</td>
<td style="text-align: right;">0.00277</td>
<td style="text-align: right;">157</td>
</tr>
<tr class="even">
<td>Nederwiek 1 (offshore allocation)</td>
<td style="text-align: right;">30,000</td>
<td style="text-align: right;">15,000</td>
<td style="text-align: right;">1,083</td>
<td style="text-align: right;">72,195</td>
<td style="text-align: right;">0.00750</td>
<td style="text-align: right;">541</td>
</tr>
<tr class="odd">
<td>Petrofac framework (allocated average)</td>
<td style="text-align: right;">30,000</td>
<td style="text-align: right;">15,000</td>
<td style="text-align: right;">906</td>
<td style="text-align: right;">60,407</td>
<td style="text-align: right;">0.00750</td>
<td style="text-align: right;">453</td>
</tr>
<tr class="even">
<td>North Sea Energy / Iv concept</td>
<td style="text-align: right;">9,500</td>
<td style="text-align: right;">4,750</td>
<td style="text-align: right;">177</td>
<td style="text-align: right;">37,351</td>
<td style="text-align: right;">0.00950</td>
<td style="text-align: right;">355</td>
</tr>
<tr class="odd">
<td>OffsH2ore concept</td>
<td style="text-align: right;">13,000</td>
<td style="text-align: right;">6,500</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">22,663</td>
<td style="text-align: right;">0.01300</td>
<td style="text-align: right;">295</td>
</tr>
<tr class="even">
<td>MHB Alpha fabrication subcontract</td>
<td style="text-align: right;">30,000</td>
<td style="text-align: right;">15,000</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">16,959</td>
<td style="text-align: right;">0.00750</td>
<td style="text-align: right;">127</td>
</tr>
</tbody>
</table>
<p>Mass evidence: HKZ Alpha <span class="citation" data-cites="petrofac2021HKZAlpha">(<a href="#ref-petrofac2021HKZAlpha" role="doc-biblioref">Petrofac 2021</a>)</span>, HKZ Beta <span class="citation" data-cites="petrofac2022HKZBeta">(<a href="#ref-petrofac2022HKZBeta" role="doc-biblioref">Petrofac 2022</a>)</span>, Nederwiek <span class="citation" data-cites="misc2024Nederwiek">(<a href="#ref-misc2024Nederwiek" role="doc-biblioref">MISC Berhad 2025</a>, printed p.&nbsp;77)</span>, Alpha <span class="citation" data-cites="mhb2023AlphaAward">(<a href="#ref-mhb2023AlphaAward" role="doc-biblioref">Malaysia Marine and Heavy Engineering Holdings Berhad 2023</a>)</span>, NSE <span class="citation" data-cites="nse2022EnergyHubs">(<a href="#ref-nse2022EnergyHubs" role="doc-biblioref">North Sea Energy 2022</a>, table 4.9)</span>, and OffsH2ore <span class="citation" data-cites="offsh2ore2023Report">(<a href="#ref-offsh2ore2023Report" role="doc-biblioref">Fraunhofer ISE and project partners 2023, 48</a>)</span>. Capacity denominators are the stated platform ratings; they are not necessarily identical electrical input boundaries across technologies.</p>
</section>
<section id="currency-and-price-year-audit" class="level3">
<h3 class="anchored" data-anchor-id="currency-and-price-year-audit">Currency and price-year audit</h3>
<p>Annual-average exchange rates per EUR: USD 1.1195 (2019), USD 1.0813 and MYR 4.9320 (2023) <span class="citation" data-cites="bundesbank2026AnnualFX">(<a href="#ref-bundesbank2026AnnualFX" role="doc-biblioref">Deutsche Bundesbank 2026</a>)</span>. Euro-area annual HICP changes: 2020: 0.3%; 2021: 2.6%; 2022: 8.4%; 2023: 5.4%; 2024: 2.4%; 2025: 2.1% <span class="citation" data-cites="eurostat2026AnnualHICP">(<a href="#ref-eurostat2026AnnualHICP" role="doc-biblioref">Eurostat 2026</a>)</span>.</p>
<p>The resulting inflation factors to 2025 are 1.22926 from 2019, 1.10196 from 2022, and 1.04550 from 2023. Source-year conversion precedes inflation adjustment. Consumer inflation is a transparent preliminary proxy, not an offshore fabrication or installation index.</p>
<p>HKZ: divide the combined award and summed topside masses by 2, convert USD to EUR at the assumed aggregate price year, then escalate. Nederwiek: multiply Petrofac’s own award by the assumed offshore share of 80%, convert and escalate. Framework: divide the framework value by 6, multiply by the approximate Petrofac share of 50% and the same offshore share, then escalate. The latter share is user-selected modelling judgement, not a supplier disclosure.</p>
<div id="fig-platform-benchmarks" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Platform cost versus inferred equipment mass. HVAC offshore EPCI and allocated HVDC EPCI lie above hydrogen design estimates and the fabrication-only subcontract. Framework and project awards overlap and are not independent samples.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-platform-benchmarks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/platform_epci_benchmarks.svg" class="img-fluid figure-img" alt="Platform cost versus inferred equipment mass. HVAC offshore EPCI and allocated HVDC EPCI lie above hydrogen design estimates and the fabrication-only subcontract. Framework and project awards overlap and are not independent samples.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-platform-benchmarks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Commercial offshore packages, conceptual hydrogen estimates and fabrication-only evidence against inferred equipment mass. The dashed line is a comparison assumption, not a regression.
</figcaption>
</figure>
</div>
</section>
<section id="interpretation-and-tradeoffs" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-and-tradeoffs">Interpretation and Tradeoffs</h3>
<p><strong>The commercial observations support investigating linear scaling.</strong> HKZ gives 56,673 EUR<sub>2025</sub>/equipment t; the individual Nederwiek award, with the assumed offshore allocation, gives 72,195 EUR<sub>2025</sub>/equipment t. This is a useful cross-check across different masses, but there are only two distinct commercial mass levels. The framework average does not supply a third independent mass level, and its projects need not have equal prices.</p>
<p>Nederwiek’s disclosed Petrofac award is preferable to assigning every project the framework average. Its remaining weakness is the offshore/onshore allocation. HKZ avoids that allocation but differs in technology, site and contract date. The owner-procurement description supports excluding major high-voltage equipment from HKZ’s platform package; detailed auxiliary-equipment boundaries still require reconciliation <span class="citation" data-cites="tennet2021OwnerEquipment">(<a href="#ref-tennet2021OwnerEquipment" role="doc-biblioref">TenneT 2021</a>)</span>.</p>
<p><strong>The hydrogen estimates remain lower even though installation is included.</strong> The difference therefore cannot be explained solely by missing offshore installation. OffsH2ore also carries a separate 20% engineering allowance covering several activities, so its structure subtotal is not a complete commercial EPCI quote <span class="citation" data-cites="offsh2ore2023Report">(<a href="#ref-offsh2ore2023Report" role="doc-biblioref">Fraunhofer ISE and project partners 2023, sec. 6.2.8</a>)</span>. It would be misleading to apply that whole-plant allowance only to the structural subtotal and call the result scope-matched. Design maturity, equipment boundaries, site, market conditions and commercial risk may explain part of the gap; the evidence does not quantify each contribution. No matched commercial electrolyser-platform EPCI award was identified in this research.</p>
<p><strong>Inferred equipment mass is a major limitation.</strong> DNV explicitly equates topside structure mass to process-equipment mass as a rule of thumb, giving <span class="math inline">\(M_{\mathrm{top}}\approx2M_{\mathrm{eqp}}\)</span> <span class="citation" data-cites="dnv2023OffshoreHydrogen">(<a href="#ref-dnv2023OffshoreHydrogen" role="doc-biblioref">DNV 2023, 16</a>)</span>. The NSE breakdown reports 5510 t structure within 9500 t total topside <span class="citation" data-cites="nse2022EnergyHubs">(<a href="#ref-nse2022EnergyHubs" role="doc-biblioref">North Sea Energy 2022</a>, table 4.9)</span>; the remaining mass includes architectural and other items and is not a clean process-equipment measurement. This illustrates why the DNV conversion must not be presented as a measured universal ratio.</p>
<p>Applying the same structural fraction to every observation simply rescales the horizontal axis. It cannot demonstrate that equipment mass predicts cost better than complete topside mass. Actual weight breakdowns are needed to test that hypothesis. Uncertainty in this shared conversion is correlated across the points, not independent scatter that a regression can average away.</p>
<p>The combined package also hides fixed mobilisation costs and changes in lifting method, foundation type and water depth. Those remain applicability checks. An aggregate model is justified by the lack of defensible separate rates, not by proof that every underlying activity scales linearly.</p>
</section>
<section id="provisional-conclusion-and-further-evidence" class="level3">
<h3 class="anchored" data-anchor-id="provisional-conclusion-and-further-evidence">Provisional Conclusion and Further Evidence</h3>
<p>Retain <span class="math inline">\(\beta=b58fc729-690b-4000-b19f-365a4093b2ff;7B7B3C2076617220706C6174666F726D2D657063692D636F73742D7363616C696E672D6578706F6E656E742D76616C7565203E7D7D;\)</span> as the initial hypothesis. A rounded commercial comparison range is <strong>57,503–73,185 EUR<sub>2025</sub>/equipment t</strong>. This is the earlier EUR<sub>2023</sub> screening range converted to the site’s price basis; it is not a confidence interval, an exhaustive market range or a validated electrolyser-platform range. The dashed line uses its lower endpoint only to make the mass comparison visible.</p>
<p>The adopted central coefficient is <strong>62,730 EUR<sub>2025</sub>/equipment t</strong>, a modelling judgement within that range, not a fitted estimate. Its source-basis input is <code>platform-epci-unit-cost-source</code> = 60000 EUR/t on the EUR<sub>2023</sub> basis; the normalisation above derives the EUR<sub>2025</sub> value. Lower and upper screening assumptions remain sensitivity comparisons, not confidence limits. A change to the coefficient must retain its currency year and scope.</p>
<p>The intended mapping remains one equipment-mass input to one offshore EPCI output, with equipment purchase charged elsewhere. A free fitted exponent is not justified yet: it would confound mass with technology, commercial scope and the assumed offshore allocation. Sensitivity to the reference coefficient, mass conversion and allocation is more informative at this stage.</p>
<p>Additional leads remain outside the fit: DolWin beta has a published EPC scope, but its installation boundary needs reconciliation <span class="citation" data-cites="aibelDolwinBeta">(<a href="#ref-aibelDolwinBeta" role="doc-biblioref">Aibel 2026</a>)</span>; RTE’s Normandy–Oleron package combines offshore platforms and onshore converter stations <span class="citation" data-cites="rte2024HVDCFacts">(<a href="#ref-rte2024HVDCFacts" role="doc-biblioref">RTE 2024b</a>)</span>; RTE Dunkerque needs a matched mass and equipment-purchase boundary <span class="citation" data-cites="rte2024Dunkerque">(<a href="#ref-rte2024Dunkerque" role="doc-biblioref">RTE 2024a</a>)</span>. Oil-and-gas topside EPC packages require similar equipment and foundation boundary checks before transfer. Do not turn partial evidence into an EPCI point by assuming away the missing scope.</p>
<p>For future observations, retain capacity, measured and inferred masses, support structure, depth, installation method, award and price years, currency, equipment inclusions and cost allocation. Do not count parent awards and their subcontracts independently. Keep design studies as a separate comparison class. The highest-value additions are independently scoped offshore EPCI awards at intermediate masses and actual equipment-weight breakdowns.</p>
</section>
</section>
<section id="worked-example" class="level2">
<h2 class="anchored" data-anchor-id="worked-example">Why the DNV Structural Model Is Not the Total-Cost Model</h2>
<p>The earlier method estimated topside structural mass, jacket mass and pile mass, then multiplied each by a fabrication rate. DNV’s reference rates are 7500 EUR/t, 3400 EUR/t and 1500 EUR/t, respectively <span class="citation" data-cites="dnv2023OffshoreHydrogen">(<a href="#ref-dnv2023OffshoreHydrogen" role="doc-biblioref">DNV 2023, sec. 3.4</a>)</span>. Yard integration and offshore installation would then have been added separately.</p>
<p>The earlier screening comparison placed this structural estimate substantially below the commercial offshore EPCI benchmark. The discrepancy persists after separating Hitachi’s converter scope and assigning only the agreed offshore share of Petrofac’s package. MHB’s broader fabrication subcontract also exceeds the structural estimate. These comparisons show that a structural fabrication calculation cannot stand in for the cost of delivering the platform.</p>
<p>The scopes differ, so this is not evidence that DNV’s steel-cost calculation is intrinsically wrong. It shows that the unmodelled delivery scope is material and cannot be reconstructed reliably from the available separate assumptions. We therefore select commercial EPCI as the total-cost basis. The unexplained difference is not assigned wholly to installation or yard integration, and the DNV subtotal is not added to the commercial estimate.</p>
<p>The full previous equations, inputs and code are preserved outside the published site. They remain useful for physical checks and for revisiting the decomposition if better evidence becomes available.</p>
</section>
<section id="executable-interface-output-and-applicability" class="level2">
<h2 class="anchored" data-anchor-id="executable-interface-output-and-applicability">Executable Interface, Output and Applicability</h2>
<p>The model returns one offshore platform EPCI cost, together with its reference scope, mass basis, coefficient, reference mass and scaling exponent. Equipment purchase remains separately accounted for. <a href="../offshore_installation/platform_and_substation_installation.html">Platform Installation</a> explains why no separate platform installation cost is added.</p>
<p>Mass scaling does not establish installation feasibility. Large changes in topside size, foundation type, water depth or installation method may require a different reference class rather than smooth extrapolation. Water depth is initially an applicability condition; no unsupported depth correction is embedded in the total EPCI relationship. Transferring an HVDC-derived relationship to electrolysis remains a hypothesis to test.</p>
<p>Supply exactly one of <code>[platform] equipment_mass_t</code> or <code>topside_mass_t</code>, in tonnes. The latter invokes the DNV conversion above; direct equipment mass avoids that conversion for the evaluated case. Platform count is fixed at one. Alternatively, <code>mass_method = "power_scaling"</code> with <code>rated_power_gw</code> requires an adopted upstream reference mass and rating; missing references remain explicit errors. Supplying direct mass and power scaling together is rejected.</p>
<p>The nonlinear reference mass is derived from the MHB Alpha topside reference and the shared structural fraction: <span class="math inline">\(M_{\mathrm{eqp,ref}}=(1-f_S)M_{\mathrm{top,Alpha}}\)</span>. This is a mass normalisation anchor, not adoption of MHB’s fabrication price as EPCI. The coefficient and <code>platform-epci-cost-scaling-exponent</code> can be overridden in recorded sensitivity cases; the central input table remains unchanged.</p>
<p><code>physical.platform_costs</code> reports the calculation and <code>physical.platform_total_eur</code> reports its total. The ledger contains one <code>platform / epci</code> entry. A separate platform supply or installation entry alongside EPCI is rejected. The calculation requires neither a crane selection nor jacket and pile mass estimates. Any supplied depth is retained as applicability metadata; the workflow does not certify a lift plan.</p>
<p>Annual platform OPEX uses <code>platform-opex-rate</code> on the combined platform EPCI total. This rate remains unresolved and must be calibrated for that cost boundary. Hosted equipment retains its own purchase and OPEX entries.</p>
<p><strong>Decommissioning is separate from EPCI.</strong> The old installation-based proxy cannot recover platform removal cost from the combined package. <code>platform-decommissioning-cost</code> is therefore a separate, initially unresolved EUR<sub>2025</sub> input. It enters lifetime costs once and does not reduce or block the calculated platform CAPEX. Missing decommissioning blocks complete LCOH. The existing installation-based proxy still applies to separately costed non-platform installation <a href="../methodology/financial_and_price_basis.html#decommissioning">see financial treatment</a>.</p>
<p><strong>Remaining evidence work:</strong> expand the commercial sample, obtain measured equipment masses, reconcile auxiliary-equipment scope, and provide scenario mass, platform OPEX and decommissioning inputs. These gaps do not justify inventing a mass or reporting an incomplete lifetime cost as complete.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aibelDolwinBeta" class="csl-entry" role="listitem">
Aibel. 2026. <span>“DolWin Beta.”</span> <a href="https://aibel.com/project/dolwin-beta">https://aibel.com/project/dolwin-beta</a>.
</div>
<div id="ref-bundesbank2026AnnualFX" class="csl-entry" role="listitem">
Deutsche Bundesbank. 2026. <span>“Exchange Rate Statistics: ECB Reference Rates, Annual Averages.”</span> <a href="https://www.bundesbank.de/resource/blob/810486/1450441ff029c30e4e45ffd43b5e82b8/mL/ii-euro-referenzkurse-der-ezb-data.pdf">https://www.bundesbank.de/resource/blob/810486/1450441ff029c30e4e45ffd43b5e82b8/mL/ii-euro-referenzkurse-der-ezb-data.pdf</a>.
</div>
<div id="ref-dnv2023OffshoreHydrogen" class="csl-entry" role="listitem">
DNV. 2023. <em>Cost and Performance Data for Offshore Hydrogen Production</em>. Danish Energy Agency. <a href="https://ens.dk/media/2417/download">https://ens.dk/media/2417/download</a>.
</div>
<div id="ref-eurostat2026AnnualHICP" class="csl-entry" role="listitem">
Eurostat. 2026. <span>“Consumer Prices: Inflation, Annual Average HICP Rates.”</span> <a href="https://ec.europa.eu/eurostat/statistics-explained/SEPDF/cache/4176.pdf">https://ec.europa.eu/eurostat/statistics-explained/SEPDF/cache/4176.pdf</a>.
</div>
<div id="ref-offsh2ore2023Report" class="csl-entry" role="listitem">
Fraunhofer ISE and project partners. 2023. <span>“Projekt OffsH2ore: Endbericht.”</span> <a href="https://www.ise.fraunhofer.de/content/dam/ise/de/downloads/pdf/Projekt-OffsH2ore-Abschlussbericht-2023_public.pdf">https://www.ise.fraunhofer.de/content/dam/ise/de/downloads/pdf/Projekt-OffsH2ore-Abschlussbericht-2023_public.pdf</a>.
</div>
<div id="ref-mhb2023AlphaAward" class="csl-entry" role="listitem">
Malaysia Marine and Heavy Engineering Holdings Berhad. 2023. <span>“Award of Contract for the Offshore Converter Platform for the IJmuiden Ver Alpha Project.”</span> November 29. <a href="https://www.klsescreener.com/v2/announcements/view/5975975">https://www.klsescreener.com/v2/announcements/view/5975975</a>.
</div>
<div id="ref-misc2024Nederwiek" class="csl-entry" role="listitem">
MISC Berhad. 2025. <span>“Integrated Annual Report 2024: Sustainability Strategic Priorities.”</span> <a href="https://www.insage.com.my/BursaNews/Attachment/202504/20250415/MISC-AN20250415A1-4.pdf">https://www.insage.com.my/BursaNews/Attachment/202504/20250415/MISC-AN20250415A1-4.pdf</a>.
</div>
<div id="ref-nse2022EnergyHubs" class="csl-entry" role="listitem">
North Sea Energy. 2022. <em>Energy Hubs and Transport Infrastructure</em>. <a href="https://north-sea-energy.eu/storage/NSE-2020-2022-1.1-Energy-Hubs-and-Transport-Infrastructure-v2.pdf">https://north-sea-energy.eu/storage/NSE-2020-2022-1.1-Energy-Hubs-and-Transport-Infrastructure-v2.pdf</a>.
</div>
<div id="ref-petrofac2019HKZ" class="csl-entry" role="listitem">
Petrofac. 2019. <span>“Petrofac Confirms Second Dutch Wind Farm Platform.”</span> <a href="https://www.petrofac.com/media/news/petrofac-confirms-second-dutch-wind-farm-platform">https://www.petrofac.com/media/news/petrofac-confirms-second-dutch-wind-farm-platform</a>.
</div>
<div id="ref-petrofac2021HKZAlpha" class="csl-entry" role="listitem">
Petrofac. 2021. <span>“First HKZ Offshore Wind Topside Sails.”</span> <a href="https://www.petrofac.com/media/news/first-hkz-offshore-wind-topside-sails">https://www.petrofac.com/media/news/first-hkz-offshore-wind-topside-sails</a>.
</div>
<div id="ref-petrofac2022HKZBeta" class="csl-entry" role="listitem">
Petrofac. 2022. <span>“Second HKZ Offshore Wind Topside on Its Way to the North Sea.”</span> <a href="https://www.petrofac.com/media/news/second-hkz-offshore-wind-topside-on-its-way-to-the-north-sea">https://www.petrofac.com/media/news/second-hkz-offshore-wind-topside-on-its-way-to-the-north-sea</a>.
</div>
<div id="ref-petrofac2023Framework" class="csl-entry" role="listitem">
Petrofac. 2023a. <span>“Petrofac and Hitachi Energy Secure Landmark Offshore Wind Framework Worth Approximately 13 Billion Euros.”</span> <a href="https://www.petrofac.com/media/news/petrofac-and-hitachi-energy-secure-landmark-offshore-wind-framework-worth-approximately-13-billion-euros">https://www.petrofac.com/media/news/petrofac-and-hitachi-energy-secure-landmark-offshore-wind-framework-worth-approximately-13-billion-euros</a>.
</div>
<div id="ref-petrofac2023Nederwiek" class="csl-entry" role="listitem">
Petrofac. 2023b. <span>“Trading Update: 20 December 2023.”</span> <a href="https://www.petrofac.com/media/news/trading-update-20-december-2023">https://www.petrofac.com/media/news/trading-update-20-december-2023</a>.
</div>
<div id="ref-petrofac2025Prospectus" class="csl-entry" role="listitem">
Petrofac. 2025. <span>“Balance Sheet Restructuring Prospectus.”</span> <a href="https://www.petrofac.com/media/qkrlyv21/petrofac-balance-sheet-restructuring-prospectus-website.pdf">https://www.petrofac.com/media/qkrlyv21/petrofac-balance-sheet-restructuring-prospectus-website.pdf</a>.
</div>
<div id="ref-rte2024Dunkerque" class="csl-entry" role="listitem">
RTE. 2024a. <span>“Eolien En Mer: RTE Conclut Un Contrat Avec Les Chantiers de l’atlantique Pour La Conception, Construction Et Assemblage.”</span> <a href="https://www.rte-france.com/actualites/eolien-mer-rte-conclut-contrat-chantiers-atlantique-conception-construction-assemblage">https://www.rte-france.com/actualites/eolien-mer-rte-conclut-contrat-chantiers-atlantique-conception-construction-assemblage</a>.
</div>
<div id="ref-rte2024HVDCFacts" class="csl-entry" role="listitem">
RTE. 2024b. <span>“Plateformes En Mer Et Stations de Conversion a Terre: Normandie Et Oleron.”</span> <a href="https://assets.rte-france.com/prod/public/2024-05/20240502-fiche-info-cles-rte-hitachi-chantiers-atlantique.pdf">https://assets.rte-france.com/prod/public/2024-05/20240502-fiche-info-cles-rte-hitachi-chantiers-atlantique.pdf</a>.
</div>
<div id="ref-tennet2021OwnerEquipment" class="csl-entry" role="listitem">
TenneT. 2021. <span>“TenneT Transformers Go Topside on Hollandse Kust Noord Platform.”</span> <a href="https://ayop.com/en/news/tennet-transformers-go-topside-on-hollandse-kust-noord-platform/">https://ayop.com/en/news/tennet-transformers-go-topside-on-hollandse-kust-noord-platform/</a>.
</div>
</div></section></div></main> <!-- /main -->
<!-- Generated by tools/build-readiness-sidebar.js. -->
<script>
(() => {
  if (document.querySelector("script[data-readiness-sidebar]")) return;
  const stylesHref = [...document.querySelectorAll('link[rel="stylesheet"][href]')]
    .map((link) => link.getAttribute("href"))
    .find((href) => /(^|\/|\.\.\/)styles\.css(?:[?#].*)?$/.test(href));
  const rootPath = stylesHref ? stylesHref.replace(/styles\.css(?:[?#].*)?$/, "") : "";
  const script = document.createElement("script");
  script.src = rootPath + "readiness-sidebar.js";
  script.defer = true;
  script.dataset.readinessSidebar = "true";
  document.body.appendChild(script);
})();
</script>
<!-- Generated by tools/build-evidence-status.js. -->
<script>
(() => {
  if (document.querySelector("script[data-evidence-status]")) return;
  const stylesHref = [...document.querySelectorAll('link[rel="stylesheet"][href]')]
    .map((link) => link.getAttribute("href"))
    .find((href) => /(^|\/|\.\.\/)styles\.css(?:[?#].*)?$/.test(href));
  const rootPath = stylesHref ? stylesHref.replace(/styles\.css(?:[?#].*)?$/, "") : "";
  const script = document.createElement("script");
  script.src = rootPath + "evidence-status.js";
  script.defer = true;
  script.dataset.evidenceStatus = "true";
  document.body.appendChild(script);
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vverbist\.github\.io\/offshore-wind-infrastructure-encyclopedia\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>