$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$frontMatterPattern = "(?s)\A---\r?\n(?<frontmatter>.*?)\r?\n---"
$progressPattern = "(?m)^\s*completion\s*:\s*(?<progress>-?\d+(?:\.\d+)?)\s*(?:#.*)?$"

function Get-ProgressBucket {
  param([double] $Progress)

  $clamped = [Math]::Min(100, [Math]::Max(0, $Progress))
  return [int]([Math]::Round($clamped / 10, 0, [MidpointRounding]::AwayFromZero) * 10)
}

$entries = Get-ChildItem -Path $projectRoot -Recurse -Filter "*.qmd" |
  Where-Object {
    $_.FullName -notlike "*\_site\*" -and
    $_.FullName -notlike "*\.quarto\*"
  } |
  ForEach-Object {
    $text = Get-Content -Raw -LiteralPath $_.FullName

    if ($text -notmatch $frontMatterPattern) {
      return
    }

    $frontmatter = $Matches["frontmatter"]

    if ($frontmatter -notmatch $progressPattern) {
      return
    }

    $relativePath = $_.FullName.Substring($projectRoot.Length).TrimStart("\", "/") -replace "\\", "/"
    $htmlPath = $relativePath -replace "\.qmd$", ".html"

    [pscustomobject]@{
      path = $htmlPath
      progress = Get-ProgressBucket ([double] $Matches["progress"])
    }
  } |
  Sort-Object path

$progressJson = ConvertTo-Json -InputObject @($entries) -Depth 3 -Compress

if ([string]::IsNullOrWhiteSpace($progressJson)) {
  $progressJson = "[]"
}

$scriptTemplate = @'
// Generated by tools/build-progress-sidebar.ps1. Edit completion in page front matter.
(() => {
  const entries = __PROGRESS_ENTRIES__;
  const alphaByProgress = new Map([
    [0, 0.16],
    [10, 0.24],
    [20, 0.32],
    [30, 0.40],
    [40, 0.48],
    [50, 0.56],
    [60, 0.64],
    [70, 0.74],
    [80, 0.84],
    [90, 0.92],
    [100, 1.00],
  ]);

  const progressByPath = new Map(
    entries.map(({ path, progress }) => [path, normaliseProgress(progress)])
  );

  const sortedPaths = [...progressByPath.keys()].sort((a, b) => b.length - a.length);

  function normaliseProgress(progress) {
    const numericProgress = Number(progress);
    if (!Number.isFinite(numericProgress)) {
      return null;
    }

    const clampedProgress = Math.min(100, Math.max(0, numericProgress));
    return Math.round(clampedProgress / 10) * 10;
  }

  function progressForHref(href) {
    if (!href) {
      return null;
    }

    let pathname;

    try {
      pathname = decodeURIComponent(new URL(href, window.location.href).pathname);
    } catch {
      return null;
    }

    pathname = pathname.replace(/\\/g, "/").replace(/\/+$/, "");

    for (const path of sortedPaths) {
      if (pathname.endsWith("/" + path) || pathname.endsWith(path)) {
        return progressByPath.get(path);
      }
    }

    return null;
  }

  function applyProgress(link, progress, label) {
    if (!link || progress === null) {
      return;
    }

    const alpha = alphaByProgress.get(progress) ?? 1;
    const text = link.textContent.trim();

    link.dataset.progress = String(progress);
    link.style.setProperty("--progress-alpha", String(alpha));
    link.setAttribute("title", `${text}: ${progress}% ${label}`);
  }

  function applySidebarProgress() {
    document.querySelectorAll("#quarto-sidebar a.sidebar-link[href]").forEach((link) => {
      applyProgress(link, progressForHref(link.getAttribute("href")), "complete");
    });

    document.querySelectorAll("#quarto-sidebar .sidebar-item-section").forEach((section) => {
      const childLinks = [
        ...section.querySelectorAll("ul.sidebar-section a.sidebar-link[data-progress]"),
      ];

      if (childLinks.length === 0) {
        return;
      }

      const averageProgress = childLinks.reduce(
        (sum, link) => sum + Number(link.dataset.progress),
        0
      ) / childLinks.length;

      const sectionLink = section.querySelector(
        ":scope > .sidebar-item-container > .sidebar-link"
      );

      applyProgress(sectionLink, normaliseProgress(averageProgress), "average complete");
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", applySidebarProgress);
  } else {
    applySidebarProgress();
  }
})();
'@

$script = $scriptTemplate.Replace("__PROGRESS_ENTRIES__", $progressJson).TrimStart([char]0xFEFF)

$html = @'
<!-- Generated by tools/build-progress-sidebar.ps1. -->
<script>
(() => {
  if (document.querySelector("script[data-progress-sidebar]")) {
    return;
  }

  const stylesHref = [...document.querySelectorAll('link[rel="stylesheet"][href]')]
    .map((link) => link.getAttribute("href"))
    .find((href) => /(^|\/|\.\.\/)styles\.css(?:[?#].*)?$/.test(href));

  const rootPath = stylesHref ? stylesHref.replace(/styles\.css(?:[?#].*)?$/, "") : "";
  const script = document.createElement("script");

  script.src = rootPath + "progress-sidebar.js";
  script.defer = true;
  script.dataset.progressSidebar = "true";

  document.body.appendChild(script);
})();
</script>
'@.TrimStart([char]0xFEFF)

$scriptPath = Join-Path $projectRoot "progress-sidebar.js"
$htmlPath = Join-Path $projectRoot "progress-sidebar.html"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($scriptPath, $script, $utf8NoBom)
[System.IO.File]::WriteAllText($htmlPath, $html, $utf8NoBom)
